import { SectionCard, SoftButton } from '../components/ui'

export function SpacePage({ setActivePage }) {
  return (
    <div className="grid gap-5 xl:grid-cols-[0.95fr_1.05fr]"><div className="space-y-5"><SectionCard><div className="flex items-center gap-4"><div className="flex h-20 w-20 items-center justify-center rounded-[28px] bg-gradient-to-br from-emerald-100 via-white to-sky-50 text-4xl">🙂</div><div><div className="text-2xl font-semibold text-slate-700">阿舟</div><div className="mt-1 text-sm text-slate-400">最近更常使用：晚间记录、陪伴式对话、睡前减压建议</div></div></div></SectionCard><SectionCard title="情绪档案摘要"><div className="grid gap-3 md:grid-cols-2">{[['高频情绪', '疲惫、焦虑、想安静一下'], ['常见时段', '晚间 21:00 - 23:30'], ['近期支持方式', '记录、呼吸放松、和 AI 聊聊'], ['状态备注', '最近需要更多恢复感与低压力输入']].map(([keyText, valueText]) => <div key={keyText} className="rounded-[22px] bg-slate-50 p-4"><div className="text-sm text-slate-400">{keyText}</div><div className="mt-2 text-sm leading-7 text-slate-600">{valueText}</div></div>)}</div></SectionCard></div><div className="space-y-5"><SectionCard title="我的入口"><div className="grid gap-3 md:grid-cols-2">{[['历史记录', '查看对话、打卡与日记', '📚'], ['报告入口', '查看历史测评报告', '📄'], ['收藏内容', '已保存的建议与练习', '⭐'], ['隐私设置', '管理记录、授权与提醒', '🔒']].map(([title, desc, emoji]) => <button key={title} onClick={() => (title === '隐私设置' ? setActivePage('privacy') : null)} className="rounded-[24px] bg-slate-50 p-5 text-left transition hover:-translate-y-0.5"><div className="text-2xl">{emoji}</div><div className="mt-3 text-sm font-medium text-slate-700">{title}</div><div className="mt-2 text-sm text-slate-500">{desc}</div></button>)}</div></SectionCard><SectionCard title="通知与支持资源"><div className="space-y-3"><div className="rounded-[22px] bg-emerald-50 p-4 text-sm leading-7 text-slate-600">每日 21:30 轻提醒：今天要不要给自己留 3 分钟？</div><div className="rounded-[22px] bg-sky-50 p-4 text-sm leading-7 text-slate-600">支持资源入口：当你需要更多帮助时，可查看危机提示页中的联系选项。</div></div></SectionCard></div></div>
  )
}

export function PrivacyPage() {
  return (
    <div className="space-y-5"><SectionCard title="隐私与安全" subtitle="你的记录值得被认真保护。"><div className="grid gap-5 xl:grid-cols-[1fr_1fr]"><div className="space-y-4">{[['数据保护说明', '你的对话、记录与测评数据仅用于平台内的陪伴、记录与状态参考服务，不会被用于公开展示。'], ['聊天记录管理', '你可以按会话删除、隐藏或导出记录。'], ['风险提醒说明', '当系统识别到较高风险波动时，会优先提供支持建议与专业资源入口。'], ['用户知情提示', '测评与 AI 回复仅用于支持与参考，不替代专业诊疗。']].map(([title, desc]) => <div key={title} className="rounded-[24px] bg-slate-50 p-5"><div className="text-sm font-medium text-slate-700">{title}</div><div className="mt-2 text-sm leading-7 text-slate-600">{desc}</div></div>)}</div><div className="space-y-4">{[['允许趋势分析', true], ['保存聊天记录', true], ['接收温和提醒', true], ['高风险时优先展示支持资源', true], ['允许导出个人记录', false]].map(([name, on]) => <div key={name} className="flex items-center justify-between rounded-[24px] bg-white p-5 shadow-sm"><div><div className="text-sm font-medium text-slate-700">{name}</div><div className="mt-1 text-xs text-slate-400">可随时调整</div></div><div className={`relative h-7 w-12 rounded-full transition ${on ? 'bg-emerald-300' : 'bg-slate-200'}`}><div className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow-sm transition ${on ? 'left-6' : 'left-1'}`} /></div></div>)}</div></div></SectionCard></div>
  )
}
